### ISSUE TITLE
Add capability for MQTT to send closing/opening

### ISSUE THREAD

**Issue by basroovers** [OpenGarage/OpenGarage-Firmware#48]
I use the Home Assistant integration to read the mqtt messages, which works like a charm for me.
But to really top it off, I would need to also receive the closing and opening events.

On the Home Assistant side it would look like this:
```
cover:
  - platform: mqtt
    name: "Garage door"
    device_class: "garage"
    state_topic: "My OpenGarage/OUT/STATE"
    command_topic: "My OpenGarage/IN/STATE"
    payload_open: "open"
    payload_close: "close"
    state_open: "OPEN"
    state_opening: "OPENING"
    state_closed: "CLOSED"
    state_closing: "CLOSING"
    optimistic: false
    retain: false
```

Documentation on this: https://www.home-assistant.io/integrations/cover.mqtt/
